"""init tables

Revision ID: 0b044c54f3a0
Revises: 
Create Date: 2025-09-22 13:39:26.697078

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b044c54f3a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('users')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_index('user_id')
        batch_op.drop_constraint('search_history_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'patients', ['patient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('search_history_ibfk_1', 'users', ['patient_id'], ['id'])
        batch_op.create_index('user_id', ['patient_id'], unique=False)

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.alter_column('rating',
               existing_type=mysql.INTEGER(),
               nullable=True)

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('mobile', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('login_count', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), server_default=sa.text("'logout'"), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('bio', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)

    # ### end Alembic commands ###
